import { useState } from "react";
import { CalendarDays, CheckCircle2, Clock3, LockKeyhole, MapPin, QrCode, Search, ShieldCheck, Star, Trophy, Zap } from "lucide-react";
import { Link } from "@tanstack/react-router";
import { Button } from "@/components/ui/button";
import { IMG, Kicker, Page, Panel, SectionTitle } from "./shared";

const sports=["Football / Futsal","Box Cricket","Badminton Court","All Sports"];
const cats=[
  {title:"Football & Futsal",sub:"5v5, 6v6 & 7v7 Professional AstroTurf",img:IMG.football,count:"26 Venues Active",price:"৳2,200",cta:"Browse Pitches"},
  {title:"Box Cricket",sub:"360° Enclosed Cages with True-Bounce Mats",img:IMG.cricket,count:"14 Venues Active",price:"৳1,800",cta:"Browse Cages"},
  {title:"Badminton Courts",sub:"Indoor Synthetic Multi-Layer Cushioning",img:IMG.badminton,count:"8 Venues Active",price:"৳1,500",cta:"Browse Courts"},
];
const arenas=[
 {name:"Apex Arena Futsal",area:"Block L, Road 11, Bashundhara R/A",price:"৳2,800",img:IMG.football,rating:"4.9 (142)"},
 {name:"KickOff Stadium Gulshan",area:"Rooftop 8th Floor, Gulshan Avenue",price:"৳3,500",img:IMG.arena2,rating:"4.8 (98)"},
 {name:"Skyline Turf Dhanmondi",area:"Road 27 (Old), Dhanmondi",price:"৳2,400",img:IMG.arena3,rating:"4.9 (210)"},
];

export function HomeScreen(){
 const [sport,setSport]=useState(sports[0]); const [searched,setSearched]=useState(false);
 return <Page className="bg-workspace">
  <section className="bg-navy text-nav-foreground"><div className="mx-auto max-w-[1220px] px-5 pb-20 pt-8">
   <div className="mb-7 inline-flex rounded-full bg-nav-input px-4 py-2 text-xs"><b className="text-primary">14 matches live now</b><span className="mx-2">•</span>8 evening slots remaining in Gulshan & Banani</div>
   <div className="grid items-center gap-10 md:grid-cols-[1.2fr_.9fr]">
    <div><h1 className="max-w-2xl text-4xl font-bold leading-[1.05] sm:text-5xl">Find Your Pitch.<br/><span className="text-primary">Book in 60 Seconds.</span></h1><p className="mt-5 max-w-2xl text-base leading-7 text-nav-muted">Bangladesh's premier multi-sport turf reservation network. Real-time pitch grid synchronization, guaranteed zero double-bookings, and instant bKash & Nagad verification.</p><div className="mt-6 flex flex-wrap gap-6 text-xs font-semibold"><span className="flex gap-2"><ShieldCheck className="size-4 text-primary"/>48+ Verified Arenas</span><span className="flex gap-2"><LockKeyhole className="size-4 text-primary"/>5-Min Slot Hold Lock</span><span className="flex gap-2"><QrCode className="size-4 text-primary"/>Instant Digital Entry Pass</span></div></div>
    <div className="relative overflow-hidden rounded-lg"><img src={IMG.hero} alt="Featured stadium at night" className="h-72 w-full object-cover"/><div className="absolute inset-x-0 bottom-0 bg-image-caption p-5"><Kicker>Featured Stadium Tonight</Kicker><div className="flex items-end justify-between"><div><b className="text-lg">Apex Arena • Pitch 1</b><p className="text-xs text-nav-muted">Bashundhara R/A • 7-a-Side FIFA Grade</p></div><span className="rounded bg-primary px-3 py-2 text-xs font-bold">OPEN 20:00</span></div></div></div>
   </div>
   <Panel className="-mb-32 mt-10 p-5 text-foreground shadow-xl"><div className="mb-5 flex flex-wrap gap-2">{sports.map(x=><Button key={x} size="sm" variant={sport===x?"default":"secondary"} onClick={()=>setSport(x)}>{x}</Button>)}</div><div className="grid gap-3 md:grid-cols-[1fr_1fr_1.15fr_1fr]">{[[MapPin,"Location / Zone","All Dhaka Hubs"],[CalendarDays,"Match Day","Today, 24 Oct"],[Clock3,"Preferred Time Slot","Evening Prime (6:00 PM - 10:00 PM)"]].map(([Icon,l,v])=><label key={l as string} className="block"><span className="mb-2 block text-[10px] font-bold uppercase tracking-widest text-muted-foreground">{l as string}</span><span className="flex h-12 items-center gap-3 rounded-md bg-secondary px-4 text-xs font-semibold"><Icon className="size-4 text-primary"/>{v as string}</span></label>)}<Button className="mt-auto h-12" onClick={()=>setSearched(true)}><Search/> {searched?"48 turfs found":"Search 48+ Turfs"}</Button></div></Panel>
  </div></section>
  <div className="mt-12 border-y border-border bg-info-strip py-3"><div className="mx-auto flex max-w-[1220px] flex-wrap justify-between gap-3 px-5 text-xs font-semibold"><span><LockKeyhole className="mr-2 inline size-3 text-primary"/>Instant Lock Technology Enabled: Chosen slots reserved exclusively for 5 minutes during checkout.</span><span className="flex gap-6"><b><Zap className="mr-1 inline size-3 text-primary"/>0% Convenience Fee</b><b><ShieldCheck className="mr-1 inline size-3"/>SSL 256-bit Secure</b></span></div></div>
  <section className="mx-auto max-w-[1220px] px-5 py-10"><div className="mb-7 flex flex-wrap items-end justify-between gap-3"><div><Kicker>Specialized Arenas</Kicker><SectionTitle>Book By Sport Category</SectionTitle></div><p className="max-w-md text-xs leading-5 text-muted-foreground">Every arena is audited for shock absorption, floodlight lux ratings, perimeter net tension, and referee facilities.</p></div><div className="grid gap-5 md:grid-cols-3">{cats.map(c=><Panel key={c.title} className="overflow-hidden shadow-sm"><div className="relative"><img src={c.img} alt={c.title} className="h-48 w-full object-cover"/><b className="absolute right-3 top-3 rounded-full bg-background px-3 py-1 text-[10px]">{c.count}</b><div className="absolute inset-x-0 bottom-0 bg-image-caption p-4 text-nav-foreground"><h3 className="text-lg font-bold">{c.title}</h3><p className="text-xs text-nav-muted">{c.sub}</p></div></div><div className="space-y-3 p-4 text-xs text-muted-foreground">{["Professional-grade playing surface","LED glare-free floodlights","Bibs, balls & whistles included"].map(x=><p key={x}><CheckCircle2 className="mr-2 inline size-4 text-primary"/>{x}</p>)}<div className="flex items-end justify-between pt-2 text-foreground"><b>From <span className="text-primary">{c.price}</span>/hr</b><span className="text-primary font-bold">{c.cta} →</span></div></div></Panel>)}</div></section>
  <section className="mx-auto max-w-[1220px] px-5 pb-16 pt-6"><div className="mb-6 flex items-end justify-between"><div><Kicker>Tonight's Top Picks</Kicker><SectionTitle>Trending Arenas Near You</SectionTitle></div><div className="hidden gap-2 sm:flex"><Button size="sm" variant="secondary">Popularity</Button><Button size="sm" variant="secondary">Lowest Price</Button></div></div><div className="grid gap-5 md:grid-cols-3">{arenas.map((a,i)=><Link to="/venue" key={a.name}><Panel className="overflow-hidden transition hover:-translate-y-1 hover:shadow-lg"><div className="relative"><img src={a.img} alt={a.name} className="h-48 w-full object-cover"/><span className="absolute left-3 top-3 rounded-full bg-navy px-3 py-1 text-[10px] font-bold text-nav-foreground"><Star className="mr-1 inline size-3 fill-current text-warning"/>{a.rating}</span>{i===0&&<span className="absolute right-3 top-3 rounded-full bg-primary px-3 py-1 text-[10px] font-bold text-primary-foreground">Tonight: 8:00 PM Open</span>}</div><div className="p-5"><div className="flex justify-between gap-3"><h3 className="text-lg font-bold">{a.name}</h3><b className="text-lg text-primary">{a.price}<small className="text-[10px] text-muted-foreground">/hr</small></b></div><p className="mt-2 text-xs text-muted-foreground"><MapPin className="mr-1 inline size-3"/>{a.area}</p><div className="mt-4 flex gap-2"><span className="chip">Floodlights</span><span className="chip">Parking</span><span className="chip"><Trophy className="inline size-3"/> Pro Turf</span></div></div></Panel></Link>)}</div></section>
 </Page>
}