import { useState } from "react";
import { CalendarClock, CircleDollarSign, Clock3, Plus, ReceiptText, Settings2, Trophy } from "lucide-react";
import { Button } from "@/components/ui/button";
import { IMG, Page, Panel, SectionTitle, Verify } from "./shared";

const bookings=[["#TN-94021","Tariqul Islam","Pitch 1 (Futsal 7v7)","Today, 06:00 PM","bKash","৳3,200","CONFIRMED"],["#TN-94019","Arif Chowdhury","Pitch 2 (Box Cricket)","Today, 07:30 PM","Nagad","৳3,600","CONFIRMED"],["#TN-94008","Shehab Munir (Walk-in)","Pitch 1 (Futsal 7v7)","Tomorrow, 08:00 PM","Cash","৳3,400","AWAITING"]];
export function OwnerScreen(){const [active,setActive]=useState(true);const [notice,setNotice]=useState("");return <Page className="bg-workspace pb-16"><div className="mx-auto max-w-[1220px] px-5 py-6">
 <div className="flex flex-wrap items-center justify-between gap-5"><div className="flex gap-4"><img src={IMG.owner} alt="Apex Sports Hub" className="size-16 rounded-lg object-cover"/><div><h1 className="text-2xl font-bold">Apex Sports Hub</h1><Verify text="Verified Active Partner"/><p className="mt-2 text-xs text-muted-foreground">Managing 2 Certified Pitches • FIFA Quality Synthetic Grass & Box Cricket AstroTurf</p></div></div><div className="flex flex-wrap gap-2"><Button variant="secondary"><CalendarClock/>Quick Block Maintenance</Button><Button variant="secondary"><ReceiptText/>Manual Offline Entry</Button><Button><Plus/>Add New Pitch</Button></div></div>
 <div className="mt-10 grid gap-4 md:grid-cols-4">{[{l:"Monthly Gross Revenue",v:"৳4,82,500",s:"+18.4% vs. last month",icon:<CircleDollarSign className="size-5 text-primary"/>},{l:"Total Bookings (OCT)",v:"178 Matches",s:"89% pitch utilization",icon:<Trophy className="size-5 text-primary"/>},{l:"Today's Scheduled Slots",v:"8 Bookings",s:"৳24,600 projected day intake",icon:<Clock3 className="size-5 text-primary"/>},{l:"Hold Queue (Offline)",v:"2 Reservations",s:"Expires in 35m",icon:<CalendarClock className="size-5 text-primary"/>}].map(x=><Panel className="p-5" key={x.l}><div className="flex justify-between"><span className="text-[10px] font-bold uppercase tracking-widest text-muted-foreground">{x.l}</span>{x.icon}</div><b className="mt-8 block text-2xl">{x.v}</b><p className="mt-2 text-xs text-muted-foreground">{x.s}</p></Panel>)}</div>
 <Panel className="mt-8 p-6"><div className="flex flex-wrap justify-between gap-3"><SectionTitle sub="Real-time slot telemetry & instant lock manager (6:00 AM – 1:00 AM)">Live Pitch Schedule Matrix</SectionTitle><div className="flex gap-2"><Button size="sm">Pitch 1 (Futsal 7v7)</Button><Button size="sm" variant="secondary">Pitch 2 (Box Cricket)</Button></div></div><div className="my-5 rounded-md bg-success-soft p-4 text-sm"><b className="text-primary">ACTIVE MATCH NOW　</b><b>06:00 PM – 07:30 PM (90 Mins)</b><p className="mt-1 text-xs text-muted-foreground">Captain: <b>Tariqul Islam</b> • Full Payment bKash Verified (৳3,200)</p></div><div className="grid gap-2 md:grid-cols-4">{["Morning Fitness FC","Dhaka Warriors Academy","Turf Grooming & Infill","North South Titans","Dhaka Mavericks 7s","Bashundhara Super 11","Corporate IT Cup Semis","Open Slot Available"].map((x,i)=><div key={x} className={`rounded-md p-4 ${i===4?"bg-success-soft":"bg-secondary"}`}><span className="text-[10px] font-bold text-muted-foreground">{["06:00","08:00","10:00","03:30","06:00","07:30","09:00","10:30"][i]} PM</span><b className="mt-3 block text-sm">{x}</b><p className="mt-2 text-[10px] text-muted-foreground">{i===7?"Base rate ৳3,000/hr":i===2?"Staff Maintenance Block":"Completed • ৳3,200"}</p></div>)}</div></Panel>
 <div className="mt-8 grid gap-7 md:grid-cols-[1.3fr_.9fr]"><Panel className="p-6"><SectionTitle sub="Peak occupancy clusters dictate surge pricing algorithms">Weekly Demand & Hourly Heatmap</SectionTitle><div className="mt-5 grid grid-cols-7 gap-2 text-center text-[10px] font-bold">{["Day","06–10","10–02","02–06","06–09","09–12","12–02",...[["Sat","60%","30%","75%","98%","94%","40%"],["Sun","40%","25%","50%","90%","82%","20%"],["Thu","45%","30%","65%","100%","100%","70%"],["Fri","85%","55%","92%","100%","100%","88%"]].flat()].map((x,i)=><div key={i} className={`${i>6&&i%7>3?"bg-primary text-primary-foreground":"bg-secondary"} rounded py-3`}>{x}</div>)}</div></Panel><Panel className="p-6"><div className="flex justify-between"><SectionTitle>Facility Switches</SectionTitle><span className="chip">SMART IOT ON</span></div>{[["Pitch 1 Floodlights",true],["Robo-Bowler Machine",false],["Synthetic Turf Drainage",true]].map(([x,on])=><div key={x as string} className="mt-4 flex items-center justify-between rounded-md bg-secondary p-4 text-xs"><b>{x as string}</b><button onClick={()=>setActive(!active)} className={`rounded-full px-3 py-1 font-bold ${on&&active?"bg-primary text-primary-foreground":"bg-muted"}`}>{on&&active?"ACTIVE":"STANDBY"}</button></div>)}<Button variant="destructive" className="mt-5 w-full" onClick={()=>setNotice("Emergency lock enabled")}>Emergency Pitch Lock</Button>{notice&&<p className="mt-2 text-center text-xs text-destructive">{notice}</p>}</Panel></div>
 <Panel className="mt-8 overflow-hidden"><div className="flex flex-wrap justify-between gap-3 p-6"><SectionTitle sub="Live transaction feeds across online gateways and on-site cash receipts">Recent Bookings & Settlement Ledger</SectionTitle><div className="flex gap-2"><Button size="sm" variant="secondary">Filter</Button><Button size="sm" onClick={()=>setNotice("Booking ledger exported")}>Export CSV</Button></div></div><div className="overflow-x-auto"><table className="data-table"><thead><tr>{["Booking ID","Player / Captain","Pitch & Sport","Date & Slot","Payment","Intake","Status"].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{bookings.map(r=><tr key={r[0]}>{r.map((x,i)=><td key={x}>{i===6?<span className={x==="CONFIRMED"?"status-good":"status-warn"}>{x}</span>:x}</td>)}</tr>)}</tbody></table></div></Panel>
 </div></Page>}