import { useState } from "react";
import { Bath, Check, CircleParking, Clock3, Coffee, Dumbbell, MapPin, ShieldCheck, ShowerHead, Star, Wifi } from "lucide-react";
import { Button } from "@/components/ui/button";
import { IMG, Kicker, Page, Panel, SectionTitle, Verify } from "./shared";

const dates=["Today 14","Wed 15","Thu 16","Fri 17","Sat 18"];
const slots=["2:00 PM","3:00 PM","4:00 PM","5:00 PM","6:00 PM","7:00 PM","8:00 PM","9:00 PM","10:00 PM","11:00 PM","12:00 AM"];
const amenities=[[Dumbbell,"500-Lux Lights","Pro anti-glare LEDs"],[ShowerHead,"Hot Showers","Private cabins & soap"],[CircleParking,"Secure Parking","Space for 25+ cars"],[Coffee,"Player Dugout","Covered team benches"],[Bath,"Chilled Lounge","Hydration & cold drinks"],[Wifi,"Fiber Wi-Fi","100Mbps free player network"]] as const;

export function VenueScreen(){
 const [date,setDate]=useState(dates[0]); const [pitch,setPitch]=useState("Pitch 1 (Main Futsal)"); const [slot,setSlot]=useState("8:00 PM"); const [reserved,setReserved]=useState(false);
 return <Page className="bg-workspace pb-16"><div className="mx-auto max-w-[1220px] px-5">
  <div className="flex flex-wrap items-center justify-between gap-3 py-4 text-xs text-muted-foreground"><span>Home　›　Dhaka　›　Bashundhara R/A　›　<b className="text-foreground">Apex Arena Futsal & Cricket Complex</b></span><div className="flex gap-2"><Button size="sm" variant="outline">Save</Button><Button size="sm" variant="outline">Share</Button><Button size="sm" variant="outline">Directions</Button></div></div>
  <div className="flex flex-wrap items-end justify-between gap-4 pb-5"><div><div className="mb-2 flex flex-wrap gap-2"><Verify text="Verified Partner"/><span className="chip">Futsal 6v6 & 7v7</span><span className="chip">5 Slots Active Today</span></div><h1 className="text-3xl font-bold">Apex Arena Futsal & Cricket Complex</h1><p className="mt-2 text-xs text-muted-foreground"><Star className="mr-1 inline size-3 fill-current text-warning"/><b>4.9</b> (184 verified reviews)　•　<MapPin className="inline size-3"/> Block L, Road 11, Bashundhara R/A, Dhaka　•　<span className="text-primary">1.2 km away</span></p></div><Panel className="flex items-center gap-5 p-3"><div><Kicker>Starts from</Kicker><b className="text-2xl text-primary">৳2,400<small className="text-xs text-muted-foreground">/hr</small></b></div><Button onClick={()=>document.getElementById("slots")?.scrollIntoView({behavior:"smooth"})}>Check Slots</Button></Panel></div>
  <div className="grid gap-2 md:grid-cols-[2fr_1fr]"><div className="relative overflow-hidden rounded-lg"><img src={IMG.hero} alt="Apex Arena main pitch" className="h-[410px] w-full object-cover"/><div className="absolute inset-x-0 bottom-0 bg-image-caption p-5 text-nav-foreground"><Kicker>Pitch 1 (Futsal)</Kicker><b className="text-lg">International Standard 60mm Monofilament Synthetic Turf</b></div></div><div className="grid grid-cols-2 gap-2">{[IMG.football,IMG.cricket,IMG.arena2,IMG.arena3].map((src,i)=><img key={src} src={src} alt={["Player dugout","Locker and showers","Arena lounge","Cricket cage"][i]} className="h-[201px] w-full rounded-lg object-cover"/>)}</div></div>
  <div className="mt-10 grid items-start gap-7 lg:grid-cols-[2fr_.9fr]"><div className="space-y-7">
   <Panel className="p-6"><SectionTitle>⚯ Pitch Specifications</SectionTitle><div className="mt-5 grid gap-3 sm:grid-cols-3">{[["Surface Grade","FIFA Pro 60mm","Monofilament Synthetic Turf with eco-cork infill"],["Dimensions","110 × 70 ft","Optimal spacing for 6v6 or fast-paced 7v7 squads"],["Weather Shield","All-Weather","Rainproof high canopy + rapid sub-surface drainage"]].map(x=><div className="rounded-md bg-secondary p-4" key={x[0]}><Kicker>{x[0]}</Kicker><b>{x[1]}</b><p className="mt-2 text-xs text-muted-foreground">{x[2]}</p></div>)}</div></Panel>
   <Panel className="p-6"><SectionTitle>☆ Premium Amenities & Gear Included</SectionTitle><div className="mt-5 grid gap-3 sm:grid-cols-2 md:grid-cols-3">{amenities.map(([Icon,t,s])=><div key={t} className="flex gap-3 rounded-md bg-secondary p-4"><Icon className="size-5 shrink-0 text-primary"/><div><b className="text-xs">{t}</b><p className="text-[11px] text-muted-foreground">{s}</p></div></div>)}</div></Panel>
   <Panel className="p-6"><SectionTitle>☷ Ground Rules & Fair Play Policy</SectionTitle><div className="mt-5 grid gap-5 md:grid-cols-2"><div className="space-y-3 text-xs">{["Footwear: Flat soles, multi-stud turf boots only.","Reporting: Arrive 10 minutes prior to slot.","Zero Spill: Chewing gum and bottled soda strictly prohibited."].map(x=><p key={x}><Check className="mr-2 inline size-4 text-primary"/>{x}</p>)}</div><div className="rounded-md bg-secondary p-4"><b className="text-sm text-primary">Cancellation & Reschedule</b><p className="mt-2 text-xs text-muted-foreground">Full 100% instant refund or free slot reschedule up to 24 hours prior to match kick-off.</p></div></div></Panel>
   <Panel className="overflow-hidden"><div className="p-6"><SectionTitle>⌖ Pitch Location & Directions</SectionTitle><p className="mt-2 text-xs text-muted-foreground">Bashundhara Residential Area, Dhaka, Bangladesh</p></div><div className="grid h-64 place-items-center bg-map-pattern text-center"><div><MapPin className="mx-auto size-10 text-primary"/><b>Apex Arena • Bashundhara R/A</b><p className="text-xs text-muted-foreground">Near Apollo Hospital / Evercare</p></div></div></Panel>
  </div><Panel id="slots" className="sticky top-20 p-5"><div className="flex justify-between rounded-md bg-secondary p-3"><div><Kicker>Standard rate</Kicker><b className="text-lg">৳2,800<small>/hr</small></b></div><div className="text-right"><Kicker>Floodlight peak</Kicker><b className="text-lg text-primary">৳3,200<small>/hr</small></b></div></div><p className="mb-2 mt-4 text-xs font-bold">Select Match Date</p><div className="grid grid-cols-5 gap-1">{dates.map(x=><button key={x} onClick={()=>setDate(x)} className={`date-choice ${date===x?"date-choice-active":""}`}>{x}</button>)}</div><div className="mt-4 grid grid-cols-2 rounded-md bg-secondary p-1">{["Pitch 1 (Main Futsal)","Pitch 2 (Cricket Cage)"].map(x=><button key={x} onClick={()=>setPitch(x)} className={`rounded px-2 py-2 text-[10px] font-bold ${pitch===x?"bg-card shadow-sm":""}`}>{x}</button>)}</div><div className="my-4 flex gap-3 text-[9px] text-muted-foreground"><span>○ Available</span><span className="text-primary">● Selected</span><span>● Booked</span></div><div className="grid grid-cols-2 gap-2">{slots.map((x,i)=>{const booked=i>=2&&i<=5;return <button disabled={booked} key={x} onClick={()=>setSlot(x)} className={`slot-choice ${slot===x?"slot-choice-active":""}`}><b>{x}</b><small>{booked?"Booked":i>=7?"৳2,800":"৳2,400 • Available"}</small></button>})}</div><div className="mt-4 rounded-md bg-hold p-4 text-xs"><Clock3 className="mr-2 inline size-4 text-warning"/>Slot held temporarily for checkout: <b className="float-right text-warning">04:42</b></div><div className="mt-4 space-y-2 rounded-md bg-secondary p-4 text-xs"><p className="flex justify-between"><span>Pitch & Time</span><b>{slot} • {date}</b></p><p className="flex justify-between"><span>Platform Fee</span><b className="text-primary">৳0 (Free)</b></p><p className="flex justify-between border-t border-border pt-3 text-base"><b>Total Payable</b><b className="text-primary">৳3,200</b></p></div><Button className="mt-4 w-full" onClick={()=>setReserved(true)}>{reserved?"Reserved — Entry Pass Ready":"Reserve This Slot"}</Button></Panel></div>
 </div></Page>
}